FROM python:3.10-slim

ENV PYTHONPATH=/app

RUN mkdir -p /app/retrieval

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY retrieval retrieval
COPY get_historical_data.py .
COPY test_bionance.sh .

CMD ["tail", "-f", "/dev/null"]
