FROM python:3.10-slim

RUN mkdir -p /app/Images

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y curl && \
    pip install -r requirements.txt && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY Images Images
COPY . .

EXPOSE 8090

CMD ["streamlit", "run", "run.py", "--server.port=8090", "--server.address=0.0.0.0"]